services:
  http:
    build:
      context: ./docker/nginx/
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - backend
  app:
    build:
      context: ./docker/php/
    volumes:
      - .:/var/www/html
    networks:
      - backend
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  db_data:
networks:
  backend: